### PR TITLE
Make building with modern toolchain possible

### PR DESCRIPTION
**Pull request by sharkwouter**
I'm still missing some parts. The newer toolchain does not come with libpspmath bundled. I'll package it.

I also need to find a solution for pspsystemctrl. I've not been able to find a source for it. This is why this PR is still a draft, because I haven't been able to get it to link to pspsystemctrl yet, so the build process still fails for me.

I had to turn a lot of errors into warnings. I think there are some overlooked bugs in this code.

### CODE REVIEW

**Comment by Fighter19** [comment]
Thanks for the contribution!
I'll look into it as well.
I currently have no idea what the functions are that required pspsystemctrl,
but there exists a library with a similar name (pspsyscon), that I have added some symbol names for.
(Seeing that both probably mean "psp system control")

https://github.com/pspdev/pspsdk/pull/23/commits/024abb63f27d5a9edd3b7a3187529a4b9c97bd96

Feel free to provide the undefined references on link time.

**Comment by sharkwouter** [comment]
Interesting, maybe I can just remove the library from linking. I'll do some testing.

**Comment by sharkwouter** [comment]
Unfortunately I am unable to package libpspmath, since it is lacking a license :(

**Comment by sharkwouter** [comment]
It builds now, could you do a final test @Fighter19?

**Comment by Fighter19** [comment]
Sure, I'll just need to install the newest toolchain first.
Might take a while.
Also, Merry Christmas :christmas_tree: :smile: !

**Comment by Fighter19** [comment]
Works fine!
Performance/size seems to be a bit worse than with the old toolchain, but that might be placebo.

**Pull request merged**
